import {PARAGRAPHS,CHAPTERS,IMAGE_META,HANDOFFS,VERIFIED_BOOK_LANGUAGES} from "./data.js";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEYS={theme:"sipsik.reader.theme",font:"sipsik.reader.fontScale",position:"sipsik.reader.position",globalLanguage:"sipsik.globalLanguage",globalLanguageStamp:"sipsik.globalLanguageStamp",bookLanguage:"sipsik.reader.bookLanguage",seenOpening:"sipsik.reader.seenOpening"};
const THEMES=["white","ivory","paper","gray"],SCALES=[.88,1,1.14,1.28];let storageOK=true;const memory=new Map();
function getStore(k,f=null){try{const v=localStorage.getItem(k);return v===null?(memory.has(k)?memory.get(k):f):v}catch{storageOK=false;return memory.has(k)?memory.get(k):f}}
function setStore(k,v){memory.set(k,String(v));try{localStorage.setItem(k,String(v))}catch{storageOK=false}}
function delStore(k){memory.delete(k);try{localStorage.removeItem(k)}catch{storageOK=false}}
const opening=$("#opening"),reader=$("#reader"),story=$("#story"),scroller=$("#storyScroller"),currentArt=$("#currentArt"),positionLabel=$("#positionLabel"),settingsDialog=$("#settingsDialog"),sizeValue=$("#sizeValue"),listenStage=$("#listenStage"),listenArt=$("#listenArt"),listenChapter=$("#listenChapter"),listenId=$("#listenId"),listenCount=$("#listenCount"),audioToggle=$("#audioToggle"),toast=$("#toast");
let theme=THEMES.includes(getStore(KEYS.theme,"ivory"))?getStore(KEYS.theme,"ivory"):"ivory";let fontScale=Number(getStore(KEYS.font,"1"));if(!SCALES.includes(fontScale))fontScale=1;let currentImage="a",currentCanonical=getStore(KEYS.position,"c01-p001");if(!PARAGRAPHS.some(p=>p.id===currentCanonical))currentCanonical="c01-p001";let narrationIndex=Math.max(0,PARAGRAPHS.findIndex(p=>p.id===currentCanonical)),speaking=false,paused=false,utterance=null,lastScrollSave=0,userHasScrolled=false;
function syncGlobalLanguageCascade(){const q=new URLSearchParams(location.search).get("globalLanguage");if(q&&q==="et"){const p=getStore(KEYS.globalLanguage,null);if(p!==q){setStore(KEYS.globalLanguage,q);setStore(KEYS.globalLanguageStamp,String(Date.now()));delStore(KEYS.bookLanguage)}}const g=getStore(KEYS.globalLanguage,"et"),b=getStore(KEYS.bookLanguage,g);if(!VERIFIED_BOOK_LANGUAGES.some(l=>l.code===b))setStore(KEYS.bookLanguage,"et")}
syncGlobalLanguageCascade();
function applyTheme(n){theme=THEMES.includes(n)?n:"ivory";document.body.classList.remove(...THEMES.map(t=>`theme-${t}`));document.body.classList.add(`theme-${theme}`);setStore(KEYS.theme,theme);$$("[data-theme]").forEach(b=>b.setAttribute("aria-checked",String(b.dataset.theme===theme)));$('meta[name="theme-color"]').setAttribute("content",getComputedStyle(document.body).getPropertyValue("--surface").trim()||"#fbfaf5")}
function applyFontScale(n){fontScale=SCALES.includes(n)?n:1;document.documentElement.style.setProperty("--font-scale",String(fontScale));setStore(KEYS.font,String(fontScale));sizeValue.textContent=`${Math.round(fontScale*100)}%`;requestAnimationFrame(()=>restoreCanonical(currentCanonical,{smooth:false,save:false}))}
applyTheme(theme);applyFontScale(fontScale);
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderStory(){story.innerHTML="";for(const c of CHAPTERS){const h=document.createElement("section");h.className="chapter-heading";h.id=`chapter-${c.id}`;h.dataset.image=c.image;h.dataset.canonical=c.first;h.innerHTML=`<p class="chapter-number">Chapter ${Number(c.id.slice(1))}</p><h2>${escapeHtml(c.title)}</h2>`;story.appendChild(h);for(const p of PARAGRAPHS.filter(p=>p.id.startsWith(c.id+"-"))){const e=document.createElement("p");e.id=p.id;e.className="story-paragraph"+(p.id==="c03-p031"?" verse":"");e.dataset.canonical=p.id;e.textContent=p.text;story.appendChild(e)}}}
renderStory();
function imageForCanonical(id){const i=PARAGRAPHS.findIndex(p=>p.id===id);if(i<0)return"a";const p=PARAGRAPHS[i];if(p.id.startsWith("c01-"))return i<14?"a":"b";if(p.id.startsWith("c02-"))return Number(p.id.slice(-3))<3?"d":"c";if(p.id.startsWith("c03-")){const n=Number(p.id.slice(-3));return n<12?"e":n<23?"f":"g"}return"a"}
function chapterNumberForCanonical(id){return Number(id.slice(1,3))||1}
function setArt(imageId,{listen=false}={}){const m=IMAGE_META[imageId]||IMAGE_META.a,t=listen?listenArt:currentArt;if((listen&&t.dataset.image===imageId)||(!listen&&currentImage===imageId))return;if(!listen)t.classList.add("is-changing");const p=new Image();p.onload=()=>{t.src=m.src;t.alt=m.alt;t.dataset.image=imageId;if(!listen){currentImage=imageId;requestAnimationFrame(()=>t.classList.remove("is-changing"))}};p.src=m.src}
function markerOffsets(){return HANDOFFS.map(h=>({...h,el:document.getElementById(h.marker)})).filter(x=>x.el).map(x=>({...x,top:x.el.offsetTop}))}
function activeHandoff(){const y=scroller.scrollTop+8,ms=markerOffsets();let a=ms[0];for(const m of ms){if(m.top<=y+1)a=m;else break}return a}
function firstVisibleParagraph(){const y=scroller.scrollTop+12,els=$$(".story-paragraph");let c=els[0];for(const e of els){if(e.offsetTop<=y)c=e;else break}return c?.id||"c01-p001"}
function syncFromScroll(){const h=activeHandoff();if(h)setArt(h.image);const id=firstVisibleParagraph();currentCanonical=id;positionLabel.textContent=`Chapter ${chapterNumberForCanonical(id)} · ${id}`;const n=performance.now();if(userHasScrolled&&n-lastScrollSave>140){setStore(KEYS.position,id);lastScrollSave=n}}
scroller.addEventListener("scroll",()=>{userHasScrolled=true;syncFromScroll()},{passive:true});
function restoreCanonical(id,{smooth=false,save=true}={}){const e=document.getElementById(id);if(!e)return;setArt(imageForCanonical(id));scroller.scrollTo({top:Math.max(0,e.offsetTop-2),behavior:smooth?"smooth":"auto"});currentCanonical=id;narrationIndex=Math.max(0,PARAGRAPHS.findIndex(p=>p.id===id));positionLabel.textContent=`Chapter ${chapterNumberForCanonical(id)} · ${id}`;if(save)setStore(KEYS.position,id)}
function showReader({restore=true}={}){opening.hidden=true;reader.hidden=false;setStore(KEYS.seenOpening,"1");requestAnimationFrame(()=>restoreCanonical(restore?currentCanonical:"c01-p001",{smooth:false,save:true}))}
function showOpening(){cancelNarration();listenStage.hidden=true;reader.hidden=true;opening.hidden=false;opening.scrollTop=0}
$("#openBook").addEventListener("click",()=>{const seen=getStore(KEYS.seenOpening,"0")==="1";showReader({restore:seen})});
$("#bookLanguage").addEventListener("click",()=>{setStore(KEYS.bookLanguage,"et");flash("Eesti is the verified story and narration language in this pilot.")});
$("#bookBeginning").addEventListener("click",()=>{settingsDialog.close();showOpening()});
$$("[data-theme]").forEach(b=>b.addEventListener("click",()=>applyTheme(b.dataset.theme)));
$("#settingsButton").addEventListener("click",()=>settingsDialog.showModal());
$("#smallerText").addEventListener("click",()=>{const i=SCALES.indexOf(fontScale);applyFontScale(SCALES[Math.max(0,i-1)])});
$("#largerText").addEventListener("click",()=>{const i=SCALES.indexOf(fontScale);applyFontScale(SCALES[Math.min(SCALES.length-1,i+1)])});
function flash(m){toast.textContent=m;toast.hidden=false;clearTimeout(flash._t);flash._t=setTimeout(()=>toast.hidden=true,2600)}
function speechSupported(){return"speechSynthesis"in window&&"SpeechSynthesisUtterance"in window}
function selectedBookLanguage(){return getStore(KEYS.bookLanguage,getStore(KEYS.globalLanguage,"et"))}
function voiceFor(lang){const v=speechSynthesis.getVoices();return v.find(x=>x.lang?.toLowerCase()===lang.toLowerCase())||v.find(x=>x.lang?.toLowerCase().startsWith(lang.slice(0,2).toLowerCase()))||null}
function updateListenState(){const p=PARAGRAPHS[narrationIndex]||PARAGRAPHS[0];currentCanonical=p.id;setArt(imageForCanonical(p.id),{listen:true});listenChapter.textContent=p.chapter;listenId.textContent=p.id;listenCount.textContent=`${narrationIndex+1} / ${PARAGRAPHS.length}`;audioToggle.textContent=speaking?(paused?"Resume":"Pause"):"Play";$$(".story-paragraph.audio-current").forEach(e=>e.classList.remove("audio-current"));document.getElementById(p.id)?.classList.add("audio-current");setStore(KEYS.position,p.id)}
function openListening(){narrationIndex=Math.max(0,PARAGRAPHS.findIndex(p=>p.id===currentCanonical));if(narrationIndex<0)narrationIndex=0;reader.hidden=true;opening.hidden=true;listenStage.hidden=false;updateListenState()}
function speakCurrent(){if(!speechSupported()){flash("Speech synthesis is not available in this browser.");return}speechSynthesis.cancel();const p=PARAGRAPHS[narrationIndex],u=new SpeechSynthesisUtterance(p.text.replace(/\n/g," ")),lang=VERIFIED_BOOK_LANGUAGES.find(x=>x.code===selectedBookLanguage())?.speech||"et-EE";u.lang=lang;const v=voiceFor(lang);if(v)u.voice=v;u.rate=.94;u.onstart=()=>{speaking=true;paused=false;utterance=u;updateListenState()};u.onend=()=>{if(utterance!==u)return;speaking=false;paused=false;if(narrationIndex<PARAGRAPHS.length-1){narrationIndex++;updateListenState();speakCurrent()}else{utterance=null;updateListenState()}};u.onerror=e=>{if(e.error==="canceled"||e.error==="interrupted")return;speaking=false;paused=false;utterance=null;updateListenState()};speechSynthesis.speak(u)}
function toggleNarration(){if(!speechSupported()){flash("Speech synthesis is not available in this browser.");return}if(speaking&&!paused){speechSynthesis.pause();paused=true;updateListenState();return}if(speaking&&paused){speechSynthesis.resume();paused=false;updateListenState();return}speakCurrent()}
function cancelNarration(){if(speechSupported())speechSynthesis.cancel();speaking=false;paused=false;utterance=null;if(!listenStage.hidden)updateListenState()}
function jumpNarration(d){cancelNarration();narrationIndex=Math.max(0,Math.min(PARAGRAPHS.length-1,narrationIndex+d));updateListenState()}
$("#listenButton").addEventListener("click",openListening);$("#audioToggle").addEventListener("click",toggleNarration);$("#audioPrev").addEventListener("click",()=>jumpNarration(-1));$("#audioNext").addEventListener("click",()=>jumpNarration(1));$("#audioStop").addEventListener("click",cancelNarration);$("#showText").addEventListener("click",()=>{cancelNarration();listenStage.hidden=true;reader.hidden=false;requestAnimationFrame(()=>restoreCanonical(currentCanonical,{smooth:false,save:true}))});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!listenStage.hidden)$("#showText").click()});
setArt("a");syncFromScroll();
window.__SIPSIK_TEST__={paragraphs:PARAGRAPHS.length,chapterCounts:Object.fromEntries(CHAPTERS.map(c=>[c.id,PARAGRAPHS.filter(p=>p.id.startsWith(c.id+"-")).length])),handoffs:HANDOFFS.map(h=>({marker:h.marker,image:h.image,canonical:h.canonical})),getState:()=>({theme,fontScale,currentCanonical,currentImage,bookLanguage:selectedBookLanguage(),storageOK,view:!listenStage.hidden?"listen":!reader.hidden?"reader":"opening"}),goTo:id=>{showReader({restore:false});requestAnimationFrame(()=>restoreCanonical(id,{smooth:false,save:true}))},theme:n=>applyTheme(n),font:s=>applyFontScale(s),openListen:()=>openListening(),showText:()=>$("#showText").click()};
